### ISSUE TITLE
Pinia

### ISSUE THREAD

**Issue by yuusheng** [yzx9/oToDo-web#2]
Why Pinia instead of Vuex? What's the difference between these two library in your opinion

**Comment by yzx9** [comment]
I choose Pinia because of its simpler API design. `Pinia` is a brand new proposal in the `Vue3` ecology since Nov 2019, and has been the default state management. `Pinia` should be the `Vuex5` in the early design, but now vue core team has given up on merging them.

FYI:
- <https://pinia.vuejs.org/introduction.html#comparison-with-vuex>
- Vue RFC #271
- Vuex #1763
- <https://www.youtube.com/watch?v=dQ5btkDrdJ8>

**Comment by yuusheng** [comment]
Got it! ❤️
